services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Dagou\BootstratpStyledContent\:
        resource: '../Classes/*'

    TYPO3\CMS\Core\Resource\FileReference: '@Dagou\BootstratpStyledContent\Resource\FileReference'